Dbz 2372 - Readme demo review edits
jbossdemocentral/debezium-demo pull request #2
Opened 2020-10-01 21:21 UTC by roldanbob

2020-10-07 17:30 UTC, hguerrero requested changes

2020-10-07 17:30 UTC, hguerrero commented on README.md
> +The components used in this scenario are deployed in the Solution Explorer, and are ready for you to use.
The components are deployed into the debezum-complete-demo namespace and the script to follow is in Solution Explorer.

2020-10-07 17:30 UTC, hguerrero commented on README.md
> +- Apache Camel Kafka Connectors
Apache Camel Kafka Connect connectors

2020-10-08 03:07 UTC, roldanbob commented
Commit 081e087 addresses the requested changes and incorporates a few further wording changes aimed at clarifying content.

2020-10-08 03:35 UTC, hguerrero commented
Thanks @roldanbob

2020-10-08 03:35 UTC, merged